---
gitian_user: vagrant
download_directory: /tmp/gitian
vm_builder_name: 'vm-builder-0.12.4+bzr494'
vm_builder_url: 'http://archive.ubuntu.com/ubuntu/pool/universe/v/vm-builder/vm-builder_0.12.4+bzr494.orig.tar.gz'
gitian_builder_url: https://github.com/devrandom/gitian-builder
gitian_builder_version: master
axe_git_repo_url: https://github.com/AXErunners/axe
axe_gitian_sigs_repo: https://github.com/AXErunners/gitian.sigs
axe_version: master
gitian_host_ip: 10.0.2.15
lxc_guest_ip: 10.0.3.5
axe_developer_pubkeys:
  - name: charlesrocket
    id: 0A0E29B7
  - name: ddude1
    id: B306325A
  - name: sparkuss
    id: 4033F6D8
